(TeX-add-style-hook
 "references"
 (lambda ()
   (LaTeX-add-bibitems
    "Suichoku"
    "IoT2009"
    "AWS-IoT"
    "Industrie4.0"
    "IIC"
    "IVI"
    "Soumu-sharing"
    "Hitachi-csmfg"
    "KATSUMURA2016"
    "FirstBuild"
    "Factory2015"
    "WU2013"
    "WU2015"
    "Ghomi2019"
    "THEKINEN2017"
    "CHIDA2019"
    "market"
    "yokoo"
    "google"
    "yahoo"
    "vickrey"
    "suginouchi"
    "Samimi2016"
    "Chu2009"))
 :bibtex)

